apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    app.kubernetes.io/name: example
  ports:
  - name: "5050"
    protocol: TCP
    port: 5050
    targetPort: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      service: example
  template:
    metadata:
      labels:
        service: example
    spec:
      containers:
      - name: example
        image: 552527590089.dkr.ecr.us-east-1.amazonaws.com/coworkingspace:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: VAR_KEY
          value: VAR_VAL
      restartPolicy: Always
